# 어쩌다 데이터 분석 with 파이썬
## CHAPTER 02 데이터 분석 기본(67~155p)

### - 라이브러리 임포트(68p)

In [1]:
import numpy as np

print(np.__version__)

1.24.3


### - 기본 배열 생성: array() (69p)

In [7]:
data_a = [5, 4, 2.5, 3, 1]
array_1 = np.array(data_a)

print(array_1)
print(data_a)
print(data_a[1])
print(array_1[1])

[5.  4.  2.5 3.  1. ]
[5, 4, 2.5, 3, 1]
4
4.0


In [24]:
array_2 = np.array([5, 4, 2.5, 3, 1])
print(array_2)
array_3 = np.array([[5, 4, 2, 'a', 1], [2, 4, 5, 3, 5]])
print(array_3)

[5.  4.  2.5 3.  1. ]
[['5' '4' '2' 'a' '1']
 ['2' '4' '5' '3' '5']]


### - ndim:  array의 갯수, shape: 0행 0열, dtype: 데이터 타입 출력 (70p)

In [25]:
print(array_3.ndim) # array의 갯수
print(array_3.shape) # 2행 5열
print(array_3.dtype) # 데이터 타입 출력

2
(2, 5)
<U11


### - 0 또는 1의 배열 생성: ones(), zeros() (70p)

In [28]:
zeros = np.zeros(10)
print(zeros)
ones = np.ones(10)
print(ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [31]:
a = np.zeros((5, 5, 3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### - 시작과 끝 수치 지정 배열 생성: arange() (71p)

In [41]:
a = range(10)
print(list(a))

b = np.arange(10)
print(b)

c = np.arange(1, 15, 3) # 시작, 종료, 단계지정(몇 씩 증가)
print(c)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]
[ 1  4  7 10 13]


### - 2.1.3 배열의 산술 연산(74p)

In [43]:
a = np.array([2, 4, 6, 8])
b = np.array([3, 4, 5, 6])
c = a * b
print(c)

# - 2.1.4 인덱싱과 슬라이싱 기초(75p)
print(c[1:3])


[ 6 16 30 48]
[16 30]


### - 배열 안의 값을 호출하는 방법

In [44]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(a[1][2])

8


### - 2.1.5 난수 생성하기 (78p)
#### - 난수 시드값 지정: seed()
#### - 난수 생성(균등분포): rand()

In [46]:
np.random.seed(1000)
a = np.random.rand(5)
print(a)

[0.65358959 0.11500694 0.95028286 0.4821914  0.87247454]


#### - 난수 생성(표준정규분포): randn()

In [47]:
b = np.random.randn(5)
print(b)

[-1.39495498 -0.5373788  -0.42204881  0.49239526 -0.64690996]


#### - 난수 생성(정수): randint()

In [106]:
c = np.random.randint(10, size = 10)
print(c)

[1 7 4 5 0 6 2 9 7 0]


In [122]:
d = np.random.randint(1, 46, size = 6)
print(d)

[38  4 32 19 13 38]


#### - 데이터 무작위 샘플링: choice()

In [136]:
data_a = [num for num in range(1, 46)]
re = np.random.choice(data_a, 6)
re = np.random.choice(data_a, 6, replace = False) # replace의 False가 중복 방지 True가 중복 허용
print(re)

[39 36 13  8 38 44]


In [144]:
data_a = [num for num in range(1, 11)] # num에 1~10까지 반복
re = np.random.choice(data_a, 6, p = [0.1, 0.1, 0.05, 0.05, 0.1, 0.2, 0.05, 0.1, 0.2, 0.05])
re1 = np.random.choice(data_a, 6, p = [0.1, 0.1, 0.05, 0.05, 0.1, 0.2, 0.05, 0.1, 0.2, 0.05], replace=False)
# [0~9]의 각 숫자마다 가중치(확률)을 부여
print(re)
print(re1)


[2 8 7 8 6 1]
[7 6 2 9 5 8]


### 2.1.6 넘파이 주요 함수 (82p)

In [199]:
data = np.random.randint(1, 100, size = 10) # 1부터 100까지 10개의 랜덤 정수 생성
print(data)
print(np.mean(data)) # - 데이터의 표준 평균
print(np.median(data)) # - 데이터의 중앙값
print(np.std(data)) # - 데이터의 표준편차
print(np.var(data)) # - 데이터의 표준분산
print(np.max(data)) # - 최댓값
print(np.min(data)) # - 최솟값
print(np.sum(data)) # - 데이터 전체 합 계산
print(np.cumsum(data)) # - 누적합과 누적곱
print(np.percentile(data, 100)) # - 사분위수


[28  1 23 67  2 97 38 30 18 97]
40.1
29.0
33.48566857627304
1121.2899999999997
97
1
401
[ 28  29  52 119 121 218 256 286 304 401]
97.0


#### - 불리언 배열 관련 함수 (86p)

In [217]:
data = [-3, 5, 6, 8, 2, -5, -4]
a = (np.array(data) > 0).sum()
print(a) # 0보다 큰 수가 4개(True는 1, False는 0) 

4


In [218]:
# 기존 방식
data = [-3, 5, 6, 8, 2, -5, -4]
cnt = 0
for num in data:
    if num > 0:
        cnt += 1
print(cnt)

4


##### - any(): 데이터 중 1개이상의 True값 존재여부를 알 수 있다, all(): 데이터 전체가 True 값인지 알려준다.

In [256]:
data1 = [-3, 5, 6, 8, 2, -5, -4]
data2 = []

dataT1 = np.array(data1)
dataT2 = np.array(data2)

dataT1.any()
# dataT2.any()

dataT1.all()
# dataT2.all()

True

#### - 정렬 관련 함수 (87p)
##### - sort()는 파괴함수로 적용 후 바로 넘기는 것(b = data_a.sort())이 아닌 적용 이후(data_a.sort() -> b = data_a)에 넘겨야한다

In [242]:
data.sort()
print(data)

data_a = np.array([3, 6, 1, 7, 8, 4])
data_a.sort()
b = data_a
print(b)

[-5, -4, -3, 2, 5, 6, 8]
[1 3 4 6 7 8]


#### - 집합 관련 함수 (87p)
##### - 중복 값 제거 하기(유일값 추출)

In [268]:
# set()
data = [1, 4, 3, 5, 1, 3, 4, 2, 6, 4]
data_a = set(data)
print(data_a)

{1, 2, 3, 4, 5, 6}


In [269]:
# unique()
data_a = np.unique(np.array(data))
print(data_a)

[1 2 3 4 5 6]


In [267]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8])
print(np.union1d(a, b)) # 합집합
print(np.intersect1d(a, b)) # 교집합
print(np.in1d(a, b)) # 불리안
print(np.setdiff1d(a, b)) # 차집합
print(np.setxor1d(a, b)) # 교집합 반대

[1 2 3 4 5 6 7 8]
[4 5]
[False False False  True  True]
[1 2 3]
[1 2 3 6 7 8]
